name: Update Philippines Holidays

on:
  schedule:
    # Run daily at 6 AM UTC (2 PM PHT)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main, master ]
    paths:
      - 'scrape_holidays.py'
      - '.github/workflows/update-holidays.yml'

jobs:
  update-holidays:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Chrome and ChromeDriver
      run: |
        # Install Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Install ChromeDriver
        CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Scrape holidays data
      env:
        HOLIDAYS_URL: 'https://publicholidays.ph/2025-dates/'
        OUTPUT_FILE: 'ph_holidays.xml'
      run: |
        echo "Starting holiday data scraping..."
        python scrape_holidays.py
        echo "Scraping completed"
        
    - name: Check if XML file was created/updated
      run: |
        if [ -f "ph_holidays.xml" ]; then
          echo "XML file exists"
          ls -la ph_holidays.xml
          echo "Content preview:"
          head -20 ph_holidays.xml
        else
          echo "XML file not found!"
          exit 1
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add the XML file
        git add ph_holidays.xml
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update Philippines holidays data - $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload XML as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ph-holidays-xml
        path: ph_holidays.xml
        retention-days: 30
        if-no-files-found: warn